package com.expense.system.entity;

public enum ExpenseStatus {
    SUBMITTED,
    DRAFT,
    PENDING_MANAGER,
    PENDING_FINANCE,
    REQUIRES_EXPLANATION,
    FLAGGED,
    ESCALATED,
    AUDIT_REVIEW,
    CLEARED,
    CONFIRMED_FRAUD,
    APPROVED,
    APPROVED_WITH_OVERRIDE,
    REJECTED,
    PAID,
    REIMBURSED,
    PENDING_SECOND_APPROVAL,
    REQUIRES_ACKNOWLEDGMENT,
    APPROVED_PENDING_PAYMENT,
    ARCHIVED
}
